server:
  port: 8180


org:
  my:
    jwt:
      #\u8DF3\u8FC7\u8BA4\u8BC1\u7684\u8DEF\u7531
      skip-auth-urls:
        - /baidu
      ############################################
      #   \u6709\u6548\u65F6\u957F
      #     \u5355\u4F4D\uFF1Ad:\u5929\u3001h:\u5C0F\u65F6\u3001m:\u5206\u949F\u3001s:\u79D2
      ###########################################
      effective-time: 7d

spring:
  application:
    name: service-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848